### PR TITLE
Removed all legislative, judicial, and non-federal agencies from current federal

### PR DESCRIPTION
**Pull request by jsf9k**
This is analogous to what is done by Pulse here: https://github.com/18F/pulse/blob/master/data/processing.py#L1151-L1175

### CODE REVIEW

**Comment by konklone** [comment]
Just as a small note, I've had to update that function before after it became less effective, to keep up with changing data fields. 

It would be nice to (in parallel) feed this problem upstream to DotGov for a clear way to delineate branches without having to keep on top of a whitelist of office names/IDs.

**Comment by h-m-f-t** [comment]
I intend to add the branch of government a domain belongs to as a column for current-federal... but can't guarantee this will happen nor its timeliness.

**Comment by konklone** [comment]
You could also possibly modify the type field to be like `Non-Federal Agency (Executive)` or something like that, without needing to add a new field to the data.

But that's for a separate issue thread :)

**Comment by jsf9k** [comment]
@dav3r and @h-m-f-t, do we want to merge this or should I just close the pull request?

**Pull request merged**
